### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ghost** [danhab99/ledcapture#2]
Hi,

I wanted to thank you for this tool, I really loved it. I have some suggestions though for more features:

- bring disk activities along with network activities
- more leds/sounds possible: keyboard backlight, Thinkpad “i“ led, sounds, PC beeps, etc...

For example, I’d love to see my Thinkpad ”i” led blinks when I have network traffic or disk activities like transfer

What do you think ? :)

**Comment by SomethingGeneric** [comment]
Disk activity would be cool, but I think that kinda ruins the name :P

But yeah, looking into other key LED's would be cool. Not sure if the thinkpad LED can be controlled from the kernel, though. You've got me thinking about the sound idea, though.

**Comment by ghost** [comment]
Hahah it’s okay, you can keep it ledcapture with disk activities also. It’ll be cool to have disk feature

The thinkpad ”i” led, as well as other microphone, sound mute leds, can be controlled through kernel with ec_sys acpi module

I have to script which uses that module to make it blink with a morse code

Take a look at this: https://www.reddit.com/r/thinkpad/comments/7n8eyu/thinkpad_led_control_under_gnulinux

**Comment by SomethingGeneric** [comment]
Could I see your output of `ls /sys/class/leds` on a ThinkPad? 

The thread you linked implies that at least some ThinkPad LED's *should* be there:
```
echo 0 | sudo tee /sys/class/leds/tpacpi\:\:kbd_backlight/brightness 1> /dev/null
echo 1 | sudo tee /sys/class/leds/tpacpi\:\:kbd_backlight/brightness 1> /dev/null
echo 2 | sudo tee /sys/class/leds/tpacpi\:\:kbd_backlight/brightness 1> /dev/null
```

**Comment by ghost** [comment]
ok, so those are all my controllable LEDs

ls -l /sys/class/leds
`input0::capslock -> ../../devices/platform/i8042/serio0/input/input0/input0::capslock`
`input0::numlock -> ../../devices/platform/i8042/serio0/input/input0/input0::numlock`
`input0::scrolllock -> ../../devices/platform/i8042/serio0/input/input0/input0::scrolllock`
`input8::capslock -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:17EF:60A9.0001/input/input8/input8::capslock`
`input8::numlock -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:17EF:60A9.0001/input/input8/input8::numlock`
`input8::scrolllock -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:17EF:60A9.0001/input/input8/input8::scrolllock`
`phy0-led -> ../../devices/pci0000:00/0000:00:1c.6/0000:3d:00.0/leds/phy0-led`
`platform::micmute -> ../../devices/platform/thinkpad_acpi/leds/platform::micmute`
`platform::mute -> ../../devices/platform/thinkpad_acpi/leds/platform::mute`
`tpacpi::kbd_backlight -> ../../devices/platform/thinkpad_acpi/leds/tpacpi::kbd_backlight`
`tpacpi::power -> ../../devices/platform/thinkpad_acpi/leds/tpacpi::power`
`tpacpi::standby -> ../../devices/platform/thinkpad_acpi/leds/tpacpi::standby`
`tpacpi::thinklight -> ../../devices/platform/thinkpad_acpi/leds/tpacpi::thinklight`
`tpacpi::thinkvantage -> ../../devices/platform/thinkpad_acpi/leds/tpacpi::thinkvantage`

And of course when I do `echo 0,1 or 2 | sudo tee /sys/class/leds/tpacpi\:\:kbd_backlight/brightness 1> /dev/null` it turn the keyboard backlight off to on

It works with other leds, like MicMute, Power, etc...

**Comment by danhab99** [comment]
I already explained it to someone else

The thing is that unless I'm selling it, I'm not interested in expanding a project beyond what I need it for. That being said I'd welcome a pull request.
